# Replace the text below to customize your site
site_name: disteln at iaac and fab lab bcn
site_description: Master in Design for Emergent Futures Documentation
site_author: stella dikmans
copyright: Copyleft 2021 "Distel" - GNU Free Documentation License
site_url: https://stella-dikmans.github.io/distel/
repo_url: 'https://stella-dikmans.github.io/distel/'


nav:
  - welcome : index.md
  - reflections :
      - performing habitation: intro.md
      - term one :
          - design studio I:
            - term I: term1/designstudioI/designstudio1.md
            - first interventions: term1/designstudioI/interventions/collectiveinterventions.md
          - bootcamp : term1/bootcamp/myfight.md
          - atlas of weak signals: term1/aows/aows.md
          - bio & agri zero: term1/bio&agri/aboutlife.md
          - living with your own ideas: term1/livingwithyourownideas/autoethnographicintervention.md
          - tech beyond the myth: term1/techbeyondthemyth/techbeyondthemyth.md
          - community engagement: term1/communityengagement/communityengagement.md
          - extended intelligences: term1/extendedintelligences/extendedintelligences.md
          - first design dialogues: term1/dialogues1/dialogues1.md
      - term two :
          - design studio II:
            - term II: term2/designstudio2/designstudio2.md
            - second interventions: term2/designstudio2/interventions2/collectiveinterventions2.md
            - future talks: term2/designstudio2/futuretalks.md
          - a billion from now: term2/billionsec/billionsec.md
          - remixing materials: term2/remixmaterials/remixmaterials.md
          - making sense and  meaning: term2/makingsense/makingsense.md
          - communicating ideas: term2/communicating/communicatingideas.md
          - digital prototyping: term2/prototyping/notes.md
          - measuring the world: term2/measuringworld/measuringworld.md
          - micro challenges: 
            - first challenge: term2/microchallenges/microchallenge.md
            - second challenge: term2/microchallenges/microchallengeII.md
          - second design dialogues: term2/dialogues2/dialogues2.md
      - research trip el hierro: trip/elhierro.md
      - term three :
          - design studio III: 
            - term III: term3/designstudio3/designstudio3.md
            - third interventions: term3/designstudio3/interventions3/collectiveinterventions3.md
          - distributed design: term3/distributeddesign/distributeddesign.md
          - prototyping: 
            - prototyping: term3/prototyping/notes.md
            - microchallenge: term3/prototyping/microchallenge/microchallengeIII.md
          - MDEF fest: term3/MDEFfest/mdeffest.md
          - design ethics: term3/designethics/designethics.md

  - masterproject :
      - in progress: masterproject/masterproject.md

  - progress :
      - drifting: progress/drifting.md
      - investigating random things: progress/investigation.md

  - context :
      - about me: context/me.md


theme:
  name: material
  palette:
    # try other colors  https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: white
    accent: purple
  font:
    # See available fonts at https://fonts.google.com/
    text: Didact Gothic
    code: Cutive Mono

  logo: images/icon.png
  favicon: images/icon.png
  features:
    - instant
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

plugins:
  - search


markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      title: On this page
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
